# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Plugins
plugins: [jekyll-paginate]

# Setup
title:            'Stat 154'
tagline:          'Modern Statistical Prediction and Machine Learning'
description:      'Modern Statistical Prediction and Machine Learning [Spring 2019] <br /> Bin Yu <br />'
url:              http://stat154.github.io
baseurl:          /

author:
  name:           'Yuansi Chen, Raaz Dwevedi'
  url:            http://stat154.github.io

paginate:         5


github:
  repo:           https://github.com/poole/hyde
